version: '3'
 
services:
  vue:
    container_name: photofallio
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8082:8080
    volumes:
      - ".:/projects"
    tty: true
